### ISSUE TITLE
Coins field missing in inventory

### ISSUE THREAD

**Issue by Gabelken** [chenasraf/dungeon-paper-app#3]
**Steps:**
1. Navigate to Inventory and attempt to add coins for a character

**Actual:**
* Coins may only be added as a custom item or added to notes

**Expected:**
* Coins should exist as a static field at the top of inventory
OR
* Coins should exist in the list of items that may be added

**Additional Notes:**
* My GM likes to use decimal money amounts, so it might be nice to allow doubles, but I don't know how common a case that is

**Comment by chenasraf** [comment]
Added in v1.0.1.
