### ISSUE TITLE
Auto-Calculate max HP using CON and class modifier

### ISSUE THREAD

**Issue by Gabelken** [chenasraf/dungeon-paper-app#4]
Would be nice if max HP was auto-generated using class base + constitution

ie. A theif with 13 CON would have 19 Max HP

**Comment by chenasraf** [comment]
Added in v1.0.1: you can select to set your max HP when changing class, and also in the edit max HP dialog, you can press the 'default' button.

New characters are created with their respective default max HP from now on.
