### ISSUE TITLE
Some looks categories not being divided into options

### ISSUE THREAD

**Issue by Gabelken** [chenasraf/dungeon-paper-app#5]
Some looks categories show the entire list as one option instead of several.

Affects:
* Thief eyes
* Paladin holy symbols

eg. 

![image](https://user-images.githubusercontent.com/20609647/59986453-2366a880-95f4-11e9-9b38-9474418620dc.png)

**Comment by chenasraf** [comment]
This is a bug in the sister repo for the DW data set, I have linked this issue there, and closing it here for the one in the correct repo.
